module IhealthBot
  module Endpoints
    class Activities < Base
      def self.create
        super('Activities') do
          category = ACTIVITY_CATEGORIES.sample
          find('#txtSportsNamebyList').set(category)
          find(:xpath, AUTOCOMPLETE_XPATH).click
        end
      end

      ACTIVITY_CATEGORIES = [
        'Aerobics, high impact',
        'Aerobics, low impact',
        'Aerobics, moderate impact',
        'American Indian Dancing, traditional',
        'Animal Care, bathing dog',
        'Archery, stationary target',
        'Automobile, repair',
        'Badminton, competitive',
        'Badminton, social',
        'Baseball',
        'Baseball - general',
        'basketball-non-game',
        'Basketball, game',
        'Basketball, nongame, general',
        'Basketball, officiating',
        'Basketball, playing in wheelchair',
        'Basketball, shooting baskets',
        'bicycling-general',
        'Bicycling, >20 mph, racing',
        'Bicycling, 10-12 mph (light)',
        'Bicycling, 12-14 mph (moderate)',
        'Bicycling, 14-16 mph (vigorous)',
        'Bicycling, 16-19 mph, racing',
        'Bicycling, BMX or mountain',
        'Bicycling, under 10mph (leisure)',
        'Bicycling, Unicycling',
        'Bike-stationary, general',
        'Bike-stationary, light',
        'Bike-stationary, vigorous',
        'Bowling, inside',
        'Boxing, in ring, general',
        'Boxing, punching bag',
        'Boxing, sparring',
        'Broomball',
        'Calisthenics, light or moderate',
        'Calisthenics, vigorous',
        'Canoeing, on camping trip',
        'Canoeing, rowing, >6 mph, vigorous effort',
        'Canoeing, rowing, light effort',
        'Canoeing, rowing, moderate effort',
        'Canoeing, rowing,crewing, competition',
        'Card playing',
        'Carpentry, general',
        'Circuit Training',
        'Cleaning, heavy, vigorous effect',
        'Cleaning,light, moderate effect',
        'Climbing, ladder',
        'Coahing Sports',
        'Cricket',
        'Croquet',
        'Curling',
        'Dancing - general',
        'Dancing, 19th Century',
        'Dancing, Aerobic, general',
        'Dancing, Aerobic, high impact',
        'Dancing, Aerobic, low impact',
        'Dancing, Aerobic, step, with 6-8 inch step',
        'Dancing, Ballet or modern',
        'Dancing, ballroom, fast',
        'Dancing, ballroom, slow',
        'Dancing, belly',
        'Dancing, chacha',
        'Dancing, country',
        'Dancing, disco',
        'Dancing, flamenco',
        'Dancing, folk',
        'Dancing, foxtrot',
        'Dancing, general',
        'Dancing, greek',
        'Dancing, hula',
        'Dancing, irish step',
        'Dancing, jazz',
        'Dancing, jitterbug',
        'Dancing, line dancing',
        'Dancing, mambo',
        'Dancing, Middle Eastern',
        'Dancing, polka',
        'Dancing, samba',
        'Dancing, square',
        'Dancing, step',
        'Dancing, swing',
        'Dancing, tango',
        'Dancing, tap',
        'Dancing, twist',
        'Dancing, waltz',
        'Darts',
        'Diving',
        'Driving, light vehicle (e.g., car, pick-up)',
        'Eating, sitting',
        'Elliptical, light',
        'Elliptical, moderate',
        'Elliptical, very vigorous',
        'Elliptical, vigorous',
        'Fencing (sport)',
        'Fishing from boat, sitting',
        'Fishing from river bank, standing',
        'Fishing in stream, in waders',
        'Fishing, general',
        'Fishing, ice, sitting',
        'Flying airplane',
        'Food, preparing, at home',
        'Football, rugby',
        'Football, tackle',
        'Forestry Work',
        'Frisbee playing, general',
        'Frisbee, ultimate',
        'Gardening',
        'Golf - general',
        'Golf, carrying clubs',
        'Golf, general',
        'Golf, miniature or driving range',
        'Golf, pulling clubs',
        'Golf, using power cart',
        'Gymnastics',
        'Hand Gliding',
        'Handball',
        'Hiking - climbing hills, 10-20 lb load',
        'Hiking - climbing hills, 21-42 lb load',
        'Hiking - climbing hills, under 10 lb load',
        'Hiking - cross country',
        'Hockey - field or ice',
        'Horseback Riding, general',
        'Horseback Riding, trotting',
        'Horseback Riding, walking',
        'House Cleaning',
        'Hunting',
        'Ice Skating - general',
        'Ice Skating, general',
        'Ice Skating, rapidly (>9mph)',
        'Ice Skating, slow, (9mph or less)',
        'Ice Skating, speed, competitive',
        'Irrigation Work (farming)',
        'Jai Alai',
        'Jazzercise,slimnastics',
        'Jogging',
        'Judo',
        'Juggling',
        'Jujitsu',
        'Jumping Jacks',
        'Jumping Rope',
        'Karate',
        'Kayaking',
        'Kick Boxing',
        'Kickball',
        'Lacrosse',
        'Laundry doing',
        'Lawn Mowing',
        'Listening to Music',
        'Long Jump',
        'Luge',
        'Meditating',
        'Moto-cross',
        'Moving furniture, household',
        'Moving household items, boxes, upstairs',
        'Moving household items, carring boxes',
        'Mowing lawn',
        'Music - listening',
        'Music Playing, accordian',
        'Music Playing, cello',
        'Music Playing, conducting',
        'Music Playing, drums',
        'Music Playing, flute',
        'Music Playing, guitar, sitting',
        'Music Playing, guitar, standing',
        'Music Playing, horn',
        'Music Playing, marcing band',
        'Music Playing, piano or organ',
        'Music Playing, trombone',
        'Music Playing, trumpet',
        'Music Playing, violin',
        'Music Playing, woodwind',
        'Operating - heavy equipment, automated',
        'Orienteering',
        'Packing and unpacking boxes',
        'Paddleball, casual',
        'Paddleboating',
        'Painting',
        'Pilates',
        'Pistol Shooting',
        'Planting, seedlings, shrubs and trees',
        'Play/walk/run with dog',
        'Polo, on horseback',
        'Pull-ups, vigorous',
        'Push-ups, vigorous',
        'Race Walking',
        'Racquetball, casual, general',
        'Racquetball, competitive',
        'Reading, sitting',
        'Reclining, reading/writing/talking',
        'Resting, sitting or lying quietly (not sleeping)',
        'Riding, in car or other vehicle',
        'Rock Climbing, ascending',
        'Rock Climbing, rappelling',
        'Roller Skating',
        'Rope jumping, fast',
        'Rope jumping, moderate',
        'Rope jumping, slow',
        'Rowing - stationary, general',
        'Rowing-stationary, light',
        'Rowing-stationary, vigorous',
        'Rowing, stationary',
        'Running',
        'running-general',
        'Running, cross-country',
        'Running, track',
        'Running, up stairs',
        'Sailing, on water or ice, casual',
        'Sailing, on water or ice, competitive',
        'Scuba Diving',
        'Sculling',
        'Sewing',
        'Sexual activity, active, vigorous',
        'Sexual activity, general, moderate',
        'Sexual activity, passive, light, kissing',
        'Shopping, groceries, with cart',
        'Shopping, groceries, without cart',
        'Shoveling, heavy (over 15 lb per min)',
        'Shoveling, light (under 10 lb per min)',
        'Shoveling, moderate (10-15 lb per min)',
        'Shuffleboard',
        'Singing, sitting',
        'Singing, standing',
        'Sitting, quietly (e.g., watching TV)',
        'Sitting, talking or talking on phone',
        'Situps, moderate',
        'Skateboarding',
        'Ski Jumping (climbing up carrying skis)',
        'Skidiving, general',
        'skiing-snow general',
        'Skiing, cross-country',
        'Skiing, downhill, light',
        'Skiing, downhill, moderate',
        'Skiing, downhill, vigorous (racing)',
        'Skiing, snow',
        'Skindiving, fast',
        'Skindiving, moderate',
        'Sky Diving',
        'Sleeping',
        'Slimnastis',
        'Smoking, sitting, quietly',
        'Snorkeling',
        'Snow Shoeing',
        'Snow, mountaineering',
        'Snowboarding, light',
        'Snowboarding, moderate',
        'Snowboarding, vigorous',
        'Snowmobiling',
        'Soccer, casual, general',
        'Soccer, competitive',
        'Softball or baseball, fast or slow pitch',
        'Softball, officiating',
        'Sparring, boxing',
        'Springboard Diving',
        'Squash',
        'Stairmaster, light',
        'Stairmaster, moderate',
        'Stairmaster, very vigorous',
        'Stairmaster, vigorous',
        'Stretching',
        'Stroller, pushing baby stroller',
        'Surfing',
        'Surfing, body or board',
        'swimming-general',
        'Swimming, backstroke',
        'Swimming, breaststroke',
        'Swimming, butterfly',
        'Swimming, crawl (50 yards/min)',
        'Swimming, crawl (75 yards/min)',
        'Swimming, freestyle, moderate',
        'Swimming, freestyle, vigorous',
        'Swimming, lake, ovean, river',
        'Swimming, leisurely, not laps',
        'Swimming, sidestroke',
        'Swimming, tread water, moderate',
        'Swimming, tread water, vigorous',
        'Table tennis, ping pong',
        'Tae Bo, moderate',
        'Tae Bo, vigorous',
        'Tae Kwon Do',
        'Tai Chi',
        'tennis-general',
        'Tennis, doubles',
        'Tennis, singles',
        'Touring, walking and riding',
        'Track and Field, discus',
        'Track and Field, hammer throw',
        'Track and Field, high jump',
        'Track and Field, hurdles',
        'Track and Field, javelin',
        'Track and Field, long jump',
        'Track and Field, pole vault',
        'Track and Field, steeplechase',
        'Trampoline',
        'TreadClimber - resistance 0 @ 1.98mph',
        'TreadClimber - resistance 1@ 1.98 mph',
        'TreadClimber - resistance 12 @ 1.98 mph',
        'TreadClimber - resistance 6 @ 1.98 mph',
        'Treadmill - 10% incline @ 2.98 mph',
        'Treadmill - 15% incline @ 2.98 mph',
        'Treadmill - 5% incline @ 2.98 mph',
        'Triple Jump',
        'TV - watching',
        'Unicycling',
        'Vacuuming',
        'Volleyball, beach',
        'Volleyball, competitive',
        'Volleyball, competitive, in gymnasium',
        'Volleyball, noncompetitive',
        'walking-under3.2km/h',
        'Walking, 2 mph, very slow',
        'Walking, 2.5 mph, slow',
        'Walking, 3 mph, moderate',
        'Walking, 3.5 mph, brisk',
        'Walking, 4 mph, very brisk',
        'Walking, 4.5 mph, fast',
        'Walking, 5 mph, very fast',
        'Walking, household',
        'Walking, marching, rapidly',
        'Walking, pushing stroller',
        'Walking, pushing wheelchair',
        'Walking, to work or class',
        'Walking, with children',
        'Walking, with the dog',
        'Water Aerobics',
        'Water Calisthenics',
        'Water Jogging',
        'Water polo',
        'Water volleyball',
        'Weight Lifting, light/moderate',
        'Weight Lifting, vigorous',
        'Whitewater rafting',
        'Wii Fit, Aerobic, Advanced step',
        'Wii Fit, Aerobic, basic run',
        'Wii Fit, Aerobic, basic step',
        'Wii Fit, Aerobic, bird\'s-eye bull\'s-eye',
        'Wii Fit, Aerobic, drving range',
        'Wii Fit, Aerobic, free step',
        'Wii Fit, Aerobic, hula hoop',
        'Wii Fit, Aerobic, island cycling',
        'Wii Fit, Aerobic, obstacle course',
        'Wii Fit, Aerobic, rhythm boxing',
        'Wii Fit, Aerobic, rhythm kung fu',
        'Wii Fit, Aerobic, rhythm parade',
        'Wii Fit, Aerobic, running plus',
        'Wii Fit, Aerobic, skateboard arena',
        'Wii Sports, baseball',
        'Wii Sports, bowling',
        'Wii Sports, boxing',
        'Wii Sports, golf',
        'Wii Sports, tennis',
        'Windsurfing',
        'Wrestling (5 min matches)',
        'Yardwork',
        'yoga'
        ]
    end
  end
end
